### ISSUE TITLE
Cross-references in vignettes do not work

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#270]
It seems that changing from
```yaml
output:
    bookdown::html_document2:
      base_format: rmarkdown::html_vignette
```

to 

```yaml
output:
    bookdown::html_vignette2:
```

broke cross-references (you can see a lot of **??** in the vignettes). But these two ooptions had to give identical results. I will try to look into this more carefully when I have time and fix or raise an issue in **bookdown**'s repo.

We should do nothing about this for now.
